spring.application.name=user-management

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagementdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET:local-dev-key}
jwt.expiration.hours=${JWT_EXPIRATION_HOURS}

spring.datasource.driver-class-name=org.postgresql.Driver